### ISSUE TITLE
Can't add object destruction to the import statement

### ISSUE THREAD

**Issue by stat92** [jonbretman/amd-to-as6#29]
Say I have next module:
```
define(['aaa'], function({aa, bb}) {
     return aa+bb;
});
```
Would be nice to get:
```
import {aa, bb} from 'aaa'
```
Now I get:
```
import from 'aaa'
```

**Comment by TJKoury** [comment]
Why is this pull not accepted yet?  Looking for the same thing....!

**Comment by stat92** [comment]
I think @jonbretman doesn't work on this project now. So you can use my fork until this merge.

**Comment by jonbretman** [comment]
My apologies for not keeping up with this project's issues. I have just merged some PR's and updated some packages and pushed 0.2.0 to npm.
